### ISSUE TITLE
Getting 599 for every request

### ISSUE THREAD

**Issue by nikolaJosifovic** [MarkHerhold/IcedFrisby#62]
Hi all,
I'm trying for few days to use IcedFrisby framework, I like it a lot.
But there is a problem where i get 599 response.

```
AssertionError: expected 599 to equal 401
   + expected - actual
      -599
      +401 
```

Is it something wrong with my code?
I'm trying same request with postman and it is working properly.

```
const  frisby = require('icedfrisby')  // Get IcedFrisby with npm install icedfrisby.
const Joi = require('joi') // Get Joi with npm install joi.

const URL = 'http://dev-cmpapi.greatplacetowork.com'

frisby.globalSetup({ // globalSetup is for ALL requests.
  request: {
    headers: {
      json: true,
      inspectOnFailure: true
    }
  }
})

frisby.create('prvi test')
  .get(URL + '/api/Client/details')
  .expectStatus(401)
  .toss()
```

package json 
```
"dependencies": {
    "mocha": "^3.4.2",
    "icedfrisby": "^1.2",
    "joi": "^10.6"
  },
```

Thanks a lot in advance

If you guys need any more info feel free to ask.

**Comment by MarkHerhold** [comment]
I think there's a certificate issue with your site. Your site redirects `http` to `https` (which is great) but it isn't obvious that it's happening because IcedFrisby silently follows the redirect. Once IcedFrisby follows the request, it hits a certificate issue and doesn't do a good job of telling you what the issue is without adding another line of code:

Try adding `.inspect((err) => console.log(err))` as below:
```js
frisby.create('prvi test')
  .get(URL + '/api/Client/details')
  .expectStatus(401)
  .inspect((err) => console.log(err))
  .toss()
```

Output:
```
  prvi test
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

To prove to myself that this isn't an IcedFrisby issue, I tried using `got` in a test node.js script and received teh same error.

```js
got.get('http://dev-cmpapi.greatplacetowork.com/api/Client/details')
```

Output:
```
> (node:4752) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: unable to verify the first certificate
```
