### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by Fishbowler** [MarkHerhold/IcedFrisby#78]
I've got a need for XML support in IcedFrisby for post body and assertions.
Doesn't look too difficult using something like [xml2js](https://www.npmjs.com/package/xml2js).
Would you accept a PR for this, or would you prefer it implemented in a plugin?

**Comment by paulmelnikow** [comment]
Hi! My preference would be to build this in a plugin, since it spreads out maintenance and keeps our dependency footprint small. It also accounts for the fact that many projects and developers will have slightly different requirements and preferences.

The easier it is to make a plugin, and the more robust our plugin community, the more we can keep things out of core which don't seem essential. We have a lot of tests and a relatively complicated core. These may be barriers to entry for some, in which case writing a plugin is potentially an easier way to contribute.

When I wrote the nock plugin, I was thinking that request interception was something many people were likely to need, and which required tests and a more esoteric thinking from the rest of Shields, and for these reasons didn't want to put it in Shields. It was also something that many people might _never_ need, so they might not want to install nock. And maybe some other JS mocking library will come along and people will want to use that instead. For these reasons I didn't want to put it in IcedFrisby.

If there's interest in maintaining plugins together, I would be fine with making an organization to do that, or simply adding each other to the plugin repos.

**Comment by Fishbowler** [comment]
Sounds reasonable. I'll get started on a plug-in just as soon as I'm finished on my current PRs.
